package com.scuola.management.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlunnoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlunnoAllPropertiesEquals(Alunno expected, Alunno actual) {
        assertAlunnoAutoGeneratedPropertiesEquals(expected, actual);
        assertAlunnoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlunnoAllUpdatablePropertiesEquals(Alunno expected, Alunno actual) {
        assertAlunnoUpdatableFieldsEquals(expected, actual);
        assertAlunnoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlunnoAutoGeneratedPropertiesEquals(Alunno expected, Alunno actual) {
        assertThat(actual)
            .as("Verify Alunno auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlunnoUpdatableFieldsEquals(Alunno expected, Alunno actual) {
        assertThat(actual)
            .as("Verify Alunno relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getCognome()).as("check cognome").isEqualTo(expected.getCognome()))
            .satisfies(a -> assertThat(a.getDataNascita()).as("check dataNascita").isEqualTo(expected.getDataNascita()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlunnoUpdatableRelationshipsEquals(Alunno expected, Alunno actual) {
        assertThat(actual)
            .as("Verify Alunno relationships")
            .satisfies(a -> assertThat(a.getClasse()).as("check classe").isEqualTo(expected.getClasse()));
    }
}
