package com.scuola.management.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CompitoInClasseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompitoInClasseAllPropertiesEquals(CompitoInClasse expected, CompitoInClasse actual) {
        assertCompitoInClasseAutoGeneratedPropertiesEquals(expected, actual);
        assertCompitoInClasseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompitoInClasseAllUpdatablePropertiesEquals(CompitoInClasse expected, CompitoInClasse actual) {
        assertCompitoInClasseUpdatableFieldsEquals(expected, actual);
        assertCompitoInClasseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompitoInClasseAutoGeneratedPropertiesEquals(CompitoInClasse expected, CompitoInClasse actual) {
        assertThat(actual)
            .as("Verify CompitoInClasse auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompitoInClasseUpdatableFieldsEquals(CompitoInClasse expected, CompitoInClasse actual) {
        assertThat(actual)
            .as("Verify CompitoInClasse relevant properties")
            .satisfies(a -> assertThat(a.getData()).as("check data").isEqualTo(expected.getData()))
            .satisfies(a -> assertThat(a.getMateria()).as("check materia").isEqualTo(expected.getMateria()))
            .satisfies(a -> assertThat(a.getRisultato()).as("check risultato").isEqualTo(expected.getRisultato()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompitoInClasseUpdatableRelationshipsEquals(CompitoInClasse expected, CompitoInClasse actual) {
        assertThat(actual)
            .as("Verify CompitoInClasse relationships")
            .satisfies(a -> assertThat(a.getAlunno()).as("check alunno").isEqualTo(expected.getAlunno()));
    }
}
